create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.content_os_workspaces (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'GENIDEIA Content OS',
  timezone text not null default 'America/Montevideo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_accounts (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  platform text not null check (platform in ('instagram','tiktok','youtube','manual')),
  external_account_id text,
  username text,
  account_type text,
  display_name text,
  avatar_url text,
  status text not null default 'pending',
  permissions jsonb not null default '[]'::jsonb,
  token_expires_at timestamptz,
  last_synced_at timestamptz,
  raw_profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, platform, external_account_id)
);

create table public.content_os_content (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  account_id uuid references public.content_os_accounts(id) on delete set null,
  platform text not null,
  external_content_id text,
  media_type text,
  media_product_type text,
  title text,
  caption text,
  permalink text,
  media_url text,
  thumbnail_url text,
  duration_seconds numeric,
  published_at timestamptz,
  status text not null default 'published',
  series_name text,
  pipeline_stage text,
  raw_media jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(account_id, external_content_id)
);

create table public.content_os_classifications (
  id uuid primary key default gen_random_uuid(),
  content_id uuid not null unique references public.content_os_content(id) on delete cascade,
  format text,
  topic text,
  subtopic text,
  hook_text text,
  hook_type text,
  intention text,
  expected_action text,
  audience text,
  cta text,
  visual_style text,
  editing_style text,
  spoken boolean,
  on_screen_text boolean,
  tools_mentioned jsonb not null default '[]'::jsonb,
  ai_confidence numeric,
  manually_reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_metric_snapshots (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  content_id uuid not null references public.content_os_content(id) on delete cascade,
  captured_at timestamptz not null default now(),
  age_minutes integer,
  views bigint,
  reach bigint,
  likes bigint,
  comments bigint,
  shares bigint,
  saves bigint,
  replies bigint,
  follows bigint,
  profile_visits bigint,
  total_interactions bigint,
  video_view_total_time_ms bigint,
  avg_watch_time_ms bigint,
  replays bigint,
  metric_payload jsonb not null default '{}'::jsonb,
  unique(content_id, captured_at)
);

create index content_os_metric_snapshots_content_time_idx on public.content_os_metric_snapshots(content_id, captured_at desc);
create index content_os_metric_snapshots_workspace_time_idx on public.content_os_metric_snapshots(workspace_id, captured_at desc);

create table public.content_os_account_snapshots (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  account_id uuid not null references public.content_os_accounts(id) on delete cascade,
  captured_at timestamptz not null default now(),
  follower_count bigint,
  reach bigint,
  profile_views bigint,
  accounts_engaged bigint,
  total_interactions bigint,
  likes bigint,
  comments bigint,
  shares bigint,
  saves bigint,
  replies bigint,
  views bigint,
  follows bigint,
  unfollows bigint,
  profile_links_taps bigint,
  metric_payload jsonb not null default '{}'::jsonb
);

create index content_os_account_snapshots_account_time_idx on public.content_os_account_snapshots(account_id, captured_at desc);

create table public.content_os_story_sequences (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  name text not null,
  intention text,
  expected_action text,
  status text not null default 'draft',
  starts_at timestamptz,
  ends_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_story_frames (
  id uuid primary key default gen_random_uuid(),
  sequence_id uuid not null references public.content_os_story_sequences(id) on delete cascade,
  content_id uuid references public.content_os_content(id) on delete set null,
  position integer not null,
  role text,
  message text,
  cta text,
  created_at timestamptz not null default now(),
  unique(sequence_id, position)
);

create table public.content_os_competitors (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  platform text not null,
  username text not null,
  external_account_id text,
  niche text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, platform, username)
);

create table public.content_os_competitor_content (
  id uuid primary key default gen_random_uuid(),
  competitor_id uuid references public.content_os_competitors(id) on delete cascade,
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  platform text not null,
  external_content_id text,
  permalink text not null,
  caption text,
  published_at timestamptz,
  public_views bigint,
  public_likes bigint,
  public_comments bigint,
  public_shares bigint,
  viral_factor numeric,
  format text,
  topic text,
  hook_text text,
  mechanism text,
  promise text,
  curiosity text,
  cta text,
  duration_seconds numeric,
  pattern_extracted boolean not null default false,
  raw_public_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, platform, permalink)
);

create table public.content_os_brand_personas (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null unique references public.content_os_workspaces(id) on delete cascade,
  name text not null default 'Constructor / Experimentador',
  promise text,
  archetype text,
  voice jsonb not null default '[]'::jsonb,
  traits jsonb not null default '[]'::jsonb,
  pillars jsonb not null default '[]'::jsonb,
  beliefs jsonb not null default '[]'::jsonb,
  signals_to_reinforce jsonb not null default '[]'::jsonb,
  perception_risks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_brand_scores (
  id bigint generated by default as identity primary key,
  content_id uuid not null references public.content_os_content(id) on delete cascade,
  brand_fit numeric,
  rationale text,
  scored_at timestamptz not null default now()
);

create table public.content_os_experiments (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  name text not null,
  hypothesis text,
  primary_variable text,
  control_values jsonb not null default '{}'::jsonb,
  test_values jsonb not null default '{}'::jsonb,
  success_metric text,
  status text not null default 'planned',
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_patterns (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  name text not null,
  dimension text,
  conditions jsonb not null default '{}'::jsonb,
  sample_size integer not null default 0,
  lift numeric,
  confidence numeric,
  target_metric text,
  status text not null default 'observing',
  explanation text,
  last_calculated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_recommendations (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  source_content_id uuid references public.content_os_content(id) on delete set null,
  pattern_id uuid references public.content_os_patterns(id) on delete set null,
  title text not null,
  rationale text,
  keep_variables jsonb not null default '{}'::jsonb,
  change_variables jsonb not null default '{}'::jsonb,
  historical_fit numeric,
  market_signal numeric,
  brand_fit numeric,
  intent_fit numeric,
  priority_score numeric,
  status text not null default 'suggested',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_leads (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  platform text,
  external_contact_id text,
  name text,
  username text,
  company text,
  contact_method text,
  source_content_id uuid references public.content_os_content(id) on delete set null,
  source_story_sequence_id uuid references public.content_os_story_sequences(id) on delete set null,
  source_detail text,
  stage text not null default 'conversation',
  interest text,
  estimated_value numeric not null default 0,
  currency text not null default 'USD',
  owner_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.content_os_leads(id) on delete cascade,
  event_type text not null,
  description text,
  channel text,
  external_event_id text,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index content_os_lead_events_lead_time_idx on public.content_os_lead_events(lead_id, occurred_at desc);

create table public.content_os_followups (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.content_os_leads(id) on delete cascade,
  action text not null,
  due_at timestamptz,
  status text not null default 'pending',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_sales (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  lead_id uuid references public.content_os_leads(id) on delete set null,
  source_content_id uuid references public.content_os_content(id) on delete set null,
  source_story_sequence_id uuid references public.content_os_story_sequences(id) on delete set null,
  amount numeric not null default 0,
  currency text not null default 'USD',
  status text not null default 'won',
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_os_attribution (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.content_os_workspaces(id) on delete cascade,
  lead_id uuid references public.content_os_leads(id) on delete cascade,
  sale_id uuid references public.content_os_sales(id) on delete cascade,
  content_id uuid references public.content_os_content(id) on delete set null,
  story_sequence_id uuid references public.content_os_story_sequences(id) on delete set null,
  touch_type text not null default 'assisted',
  weight numeric not null default 1,
  occurred_at timestamptz not null default now()
);

create table public.content_os_value_scores (
  id bigint generated by default as identity primary key,
  content_id uuid not null references public.content_os_content(id) on delete cascade,
  attention_score numeric,
  engagement_score numeric,
  relationship_score numeric,
  business_score numeric,
  calculated_at timestamptz not null default now()
);

create table public.content_os_sync_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references public.content_os_workspaces(id) on delete cascade,
  account_id uuid references public.content_os_accounts(id) on delete cascade,
  job_type text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  imported_count integer not null default 0,
  snapshot_count integer not null default 0,
  error_count integer not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create or replace view public.content_os_latest_metrics
with (security_invoker = true) as
select distinct on (m.content_id)
  m.*
from public.content_os_metric_snapshots m
order by m.content_id, m.captured_at desc;

create or replace view public.content_os_content_performance
with (security_invoker = true) as
select
  c.id,
  c.workspace_id,
  c.account_id,
  c.platform,
  c.external_content_id,
  c.title,
  c.caption,
  c.permalink,
  c.media_type,
  c.media_product_type,
  c.duration_seconds,
  c.published_at,
  cl.format,
  cl.topic,
  cl.hook_type,
  cl.intention,
  cl.expected_action,
  cl.audience,
  lm.views,
  lm.reach,
  lm.likes,
  lm.comments,
  lm.shares,
  lm.saves,
  lm.replies,
  lm.follows,
  lm.profile_visits,
  lm.avg_watch_time_ms,
  case when coalesce(lm.reach,0) > 0 then lm.saves::numeric / lm.reach else null end as save_rate,
  case when coalesce(lm.reach,0) > 0 then lm.shares::numeric / lm.reach else null end as share_rate,
  case when coalesce(lm.reach,0) > 0 then lm.follows::numeric / lm.reach else null end as follow_rate,
  case when coalesce(c.duration_seconds,0) > 0 and lm.avg_watch_time_ms is not null then (lm.avg_watch_time_ms / 1000.0) / c.duration_seconds else null end as watch_ratio
from public.content_os_content c
left join public.content_os_classifications cl on cl.content_id = c.id
left join public.content_os_latest_metrics lm on lm.content_id = c.id;

do $$
declare t text;
begin
  foreach t in array array[
    'content_os_workspaces','content_os_accounts','content_os_content','content_os_classifications',
    'content_os_metric_snapshots','content_os_account_snapshots','content_os_story_sequences','content_os_story_frames',
    'content_os_competitors','content_os_competitor_content','content_os_brand_personas','content_os_brand_scores',
    'content_os_experiments','content_os_patterns','content_os_recommendations','content_os_leads','content_os_lead_events',
    'content_os_followups','content_os_sales','content_os_attribution','content_os_value_scores','content_os_sync_runs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

create policy workspace_owner_all on public.content_os_workspaces for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create or replace function public.content_os_user_owns_workspace(target_workspace uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.content_os_workspaces w where w.id = target_workspace and w.owner_id = auth.uid());
$$;

create policy accounts_owner_all on public.content_os_accounts for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy content_owner_all on public.content_os_content for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy snapshots_owner_all on public.content_os_metric_snapshots for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy account_snapshots_owner_all on public.content_os_account_snapshots for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy story_sequences_owner_all on public.content_os_story_sequences for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy competitors_owner_all on public.content_os_competitors for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy competitor_content_owner_all on public.content_os_competitor_content for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy brand_personas_owner_all on public.content_os_brand_personas for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy experiments_owner_all on public.content_os_experiments for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy patterns_owner_all on public.content_os_patterns for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy recommendations_owner_all on public.content_os_recommendations for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy leads_owner_all on public.content_os_leads for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy sales_owner_all on public.content_os_sales for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy attribution_owner_all on public.content_os_attribution for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));
create policy sync_runs_owner_all on public.content_os_sync_runs for all using (public.content_os_user_owns_workspace(workspace_id)) with check (public.content_os_user_owns_workspace(workspace_id));

create policy classifications_owner_all on public.content_os_classifications for all using (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id))) with check (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id)));
create policy story_frames_owner_all on public.content_os_story_frames for all using (exists(select 1 from public.content_os_story_sequences s where s.id = sequence_id and public.content_os_user_owns_workspace(s.workspace_id))) with check (exists(select 1 from public.content_os_story_sequences s where s.id = sequence_id and public.content_os_user_owns_workspace(s.workspace_id)));
create policy brand_scores_owner_all on public.content_os_brand_scores for all using (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id))) with check (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id)));
create policy lead_events_owner_all on public.content_os_lead_events for all using (exists(select 1 from public.content_os_leads l where l.id = lead_id and public.content_os_user_owns_workspace(l.workspace_id))) with check (exists(select 1 from public.content_os_leads l where l.id = lead_id and public.content_os_user_owns_workspace(l.workspace_id)));
create policy followups_owner_all on public.content_os_followups for all using (exists(select 1 from public.content_os_leads l where l.id = lead_id and public.content_os_user_owns_workspace(l.workspace_id))) with check (exists(select 1 from public.content_os_leads l where l.id = lead_id and public.content_os_user_owns_workspace(l.workspace_id)));
create policy value_scores_owner_all on public.content_os_value_scores for all using (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id))) with check (exists(select 1 from public.content_os_content c where c.id = content_id and public.content_os_user_owns_workspace(c.workspace_id)));

create trigger content_os_workspaces_updated before update on public.content_os_workspaces for each row execute function public.set_updated_at();
create trigger content_os_accounts_updated before update on public.content_os_accounts for each row execute function public.set_updated_at();
create trigger content_os_content_updated before update on public.content_os_content for each row execute function public.set_updated_at();
create trigger content_os_classifications_updated before update on public.content_os_classifications for each row execute function public.set_updated_at();
create trigger content_os_story_sequences_updated before update on public.content_os_story_sequences for each row execute function public.set_updated_at();
create trigger content_os_competitors_updated before update on public.content_os_competitors for each row execute function public.set_updated_at();
create trigger content_os_competitor_content_updated before update on public.content_os_competitor_content for each row execute function public.set_updated_at();
create trigger content_os_brand_personas_updated before update on public.content_os_brand_personas for each row execute function public.set_updated_at();
create trigger content_os_experiments_updated before update on public.content_os_experiments for each row execute function public.set_updated_at();
create trigger content_os_patterns_updated before update on public.content_os_patterns for each row execute function public.set_updated_at();
create trigger content_os_recommendations_updated before update on public.content_os_recommendations for each row execute function public.set_updated_at();
create trigger content_os_leads_updated before update on public.content_os_leads for each row execute function public.set_updated_at();
create trigger content_os_followups_updated before update on public.content_os_followups for each row execute function public.set_updated_at();
create trigger content_os_sales_updated before update on public.content_os_sales for each row execute function public.set_updated_at();