import crypto from 'node:crypto';

const DEFAULT_SUPABASE_URL='https://dbwuubabafzsinaokawe.supabase.co';
const DEFAULT_WORKSPACE_ID='f2a0c61f-160c-4300-aac6-dcb8c89d98d7';
const GRAPH='https://graph.instagram.com';

function key(){return String(process.env.CONTENT_OS_SUPABASE_SECRET_KEY||process.env.CONTENT_OS_SUPABASE_SERVICE_ROLE_KEY||'').trim()||null}
function sbHeaders(extra={}){const k=key();if(!k)throw new Error('Missing CONTENT_OS_SUPABASE_SECRET_KEY');const h={apikey:k,'Content-Type':'application/json',...extra};if(!k.startsWith('sb_secret_'))h.Authorization=`Bearer ${k}`;return h}
export async function sb(path,options={}){const base=String(process.env.CONTENT_OS_SUPABASE_URL||DEFAULT_SUPABASE_URL).trim().replace(/\/$/,'');const r=await fetch(`${base}/rest/v1/${path}`,{...options,headers:{...sbHeaders(),...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null}

function directKey(){const secret=process.env.CONTENT_OS_SYNC_SECRET;if(!secret)throw new Error('Missing CONTENT_OS_SYNC_SECRET');return crypto.createHash('sha256').update(`genideia-content-os/instagram-direct/v1:${secret}`).digest()}
function encrypt(token){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',directKey(),iv);const ciphertext=Buffer.concat([cipher.update(String(token),'utf8'),cipher.final()]);return{token_ciphertext:ciphertext.toString('base64'),token_iv:iv.toString('base64'),token_tag:cipher.getAuthTag().toString('base64')}}
function decrypt(row){const d=crypto.createDecipheriv('aes-256-gcm',directKey(),Buffer.from(row.token_iv,'base64'));d.setAuthTag(Buffer.from(row.token_tag,'base64'));return Buffer.concat([d.update(Buffer.from(row.token_ciphertext,'base64')),d.final()]).toString('utf8')}

export async function persistDirectConnection({workspaceId=DEFAULT_WORKSPACE_ID,externalIdentityId,externalIdentityName,accessToken,tokenExpiresAt=null,scopes=[]}){const enc=encrypt(accessToken);const rows=await sb('content_os_connections?on_conflict=workspace_id,platform,external_identity_id',{method:'POST',headers:{Prefer:'return=representation,resolution=merge-duplicates'},body:JSON.stringify([{workspace_id:workspaceId,platform:'instagram',connection_type:'instagram_login_direct',external_identity_id:String(externalIdentityId),external_identity_name:externalIdentityName||null,...enc,token_type:'bearer',token_expires_at:tokenExpiresAt,scopes,assets:[],status:'connected',last_validated_at:new Date().toISOString()}])});return rows?.[0]||null}
export async function loadDirectConnection(workspaceId=DEFAULT_WORKSPACE_ID){const rows=await sb(`content_os_connections?workspace_id=eq.${encodeURIComponent(workspaceId)}&platform=eq.instagram&connection_type=eq.instagram_login_direct&status=eq.connected&select=*&order=updated_at.desc&limit=1`);if(!rows?.[0]?.token_ciphertext)return null;return{row:rows[0],accessToken:decrypt(rows[0])}}

async function ig(path,params,token){const u=new URL(`${GRAPH}/${path}`);Object.entries(params||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});u.searchParams.set('access_token',token);const r=await fetch(u);const t=await r.text();let p={};try{p=t?JSON.parse(t):{}}catch{}if(!r.ok)throw new Error(p?.error?.message||`Instagram Graph ${r.status}: ${t}`);return p}
function metricValue(metric){if(!metric)return null;if(metric.total_value?.value!==undefined)return metric.total_value.value;if(Array.isArray(metric.values)&&metric.values.length){const v=metric.values.at(-1)?.value;return typeof v==='object'&&v!==null?null:v}return null}
function metricsObject(payload){const out={};for(const m of payload?.data||[])out[m.name]=metricValue(m);return out}
async function mediaInsights(media,token){const common=['views','reach','likes','comments','shares','saved','total_interactions'];const reel=['follows','profile_visits','ig_reels_video_view_total_time','ig_reels_avg_watch_time','clips_replays_count'];const desired=String(media.media_product_type||'').toUpperCase()==='REELS'?[...common,...reel]:common;try{return await ig(`${media.id}/insights`,{metric:desired.join(',')},token)}catch{const data=[];for(const m of desired){try{const one=await ig(`${media.id}/insights`,{metric:m},token);if(Array.isArray(one.data))data.push(...one.data)}catch{}}return{data}}}
async function profile(token){for(const fields of ['id,user_id,username,account_type,media_count,followers_count,profile_picture_url','id,username,account_type,media_count,followers_count,profile_picture_url','id,username,account_type']){try{return await ig('me',{fields},token)}catch{}}throw new Error('No se pudo leer el perfil de Instagram')}
async function mediaList(token,limit){const fields='id,caption,media_type,media_product_type,permalink,media_url,thumbnail_url,timestamp,username';const p=await ig('me/media',{fields,limit:Math.min(100,Math.max(1,limit))},token);return p.data||[]}
async function startRun(workspaceId,accountId,jobType){const rows=await sb('content_os_sync_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{workspace_id:workspaceId,account_id:accountId,job_type:jobType,status:'running'}])});return rows?.[0]?.id||null}
async function finishRun(id,values){if(!id)return;await sb(`content_os_sync_runs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...values,finished_at:new Date().toISOString()})})}
async function mapLimit(items,limit,fn){const result=[];let i=0;async function worker(){while(i<items.length){const idx=i++;result[idx]=await fn(items[idx],idx)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return result}

export async function syncInstagramDirect({workspaceId=DEFAULT_WORKSPACE_ID,limit=25,jobType='instagram_incremental_sync'}={}){const connection=await loadDirectConnection(workspaceId);if(!connection)throw new Error('Instagram directo todavía no está autorizado para sincronización automática.');const token=connection.accessToken;const capturedAt=new Date().toISOString();const p=await profile(token);const externalId=String(p.user_id||p.id);const accountRows=await sb('content_os_accounts?on_conflict=workspace_id,platform,external_account_id',{method:'POST',headers:{Prefer:'return=representation,resolution=merge-duplicates'},body:JSON.stringify([{workspace_id:workspaceId,platform:'instagram',external_account_id:externalId,username:p.username||null,account_type:p.account_type||null,avatar_url:p.profile_picture_url||null,status:'connected',permissions:['instagram_business_basic','instagram_business_manage_insights'],last_synced_at:capturedAt,raw_profile:p}])});const accountId=accountRows?.[0]?.id;if(!accountId)throw new Error('No se pudo resolver la cuenta de Instagram en Content OS');const runId=await startRun(workspaceId,accountId,jobType);let imported=0,snapshots=0,errors=0;
try{const media=await mediaList(token,limit);await mapLimit(media,5,async(item)=>{try{const rows=await sb('content_os_content?on_conflict=account_id,external_content_id',{method:'POST',headers:{Prefer:'return=representation,resolution=merge-duplicates'},body:JSON.stringify([{workspace_id:workspaceId,account_id:accountId,platform:'instagram',external_content_id:item.id,media_type:item.media_type,media_product_type:item.media_product_type,title:(item.caption||'').split('\n')[0].slice(0,180)||null,caption:item.caption||null,permalink:item.permalink||null,media_url:item.media_url||null,thumbnail_url:item.thumbnail_url||null,published_at:item.timestamp||null,status:'published',raw_media:item}])});const contentId=rows?.[0]?.id;if(!contentId)throw new Error('No content id');imported++;const ip=await mediaInsights(item,token);const m=metricsObject(ip);const published=item.timestamp?new Date(item.timestamp).getTime():Date.now();await sb('content_os_metric_snapshots',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{workspace_id:workspaceId,content_id:contentId,captured_at:capturedAt,age_minutes:Math.max(0,Math.round((Date.now()-published)/60000)),views:m.views??null,reach:m.reach??null,likes:m.likes??null,comments:m.comments??null,shares:m.shares??null,saves:m.saved??null,replies:m.replies??null,follows:m.follows??null,profile_visits:m.profile_visits??null,total_interactions:m.total_interactions??null,video_view_total_time_ms:m.ig_reels_video_view_total_time??null,avg_watch_time_ms:m.ig_reels_avg_watch_time??null,replays:m.clips_replays_count??null,metric_payload:ip}])});snapshots++}catch(e){errors++;console.error('instagram direct media sync',item.id,e.message)}});
try{const ap=await ig('me/insights',{metric:'follower_count,reach,profile_views,accounts_engaged,total_interactions,likes,comments,shares,saves,replies,views,profile_links_taps',period:'day'},token);const a=metricsObject(ap);await sb('content_os_account_snapshots',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{workspace_id:workspaceId,account_id:accountId,captured_at:capturedAt,follower_count:a.follower_count??p.followers_count??null,reach:a.reach??null,profile_views:a.profile_views??null,accounts_engaged:a.accounts_engaged??null,total_interactions:a.total_interactions??null,likes:a.likes??null,comments:a.comments??null,shares:a.shares??null,saves:a.saves??null,replies:a.replies??null,views:a.views??null,profile_links_taps:a.profile_links_taps??null,metric_payload:ap}])})}catch(e){console.warn('account insights unavailable',e.message)}
await sb(`content_os_connections?id=eq.${encodeURIComponent(connection.row.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_validated_at:capturedAt,status:'connected'})});await finishRun(runId,{status:errors?'completed_with_errors':'completed',imported_count:imported,snapshot_count:snapshots,error_count:errors});return{ok:true,account:p.username||externalId,imported,snapshots,errors,capturedAt}}catch(e){await finishRun(runId,{status:'failed',imported_count:imported,snapshot_count:snapshots,error_count:errors+1,error_message:e.message}).catch(()=>{});throw e}}
